name: uncertainty_calculation
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.18
  - argparse
  - os
  - numpy
  - math
  - rioxarray
  - rasterio
  - matplotlib
  - scipy
  - geopandas
  - pip
  